store/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('', include('product.urls')),
    path('user/', include('user.urls')),
    path('demand/', include('demand.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    path('', views.Create.as_view(), name='create'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('reset-password/', views.ForgotPassword.as_view(), name='password_reset'),
    path('change-password/', views.ChangePassword.as_view(), name='change_password'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date, datetime
from django.forms import ValidationError
import re
from utils import validator
from django import forms

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                verbose_name='User')
    birthday = models.DateField()
    cpf = models.CharField(max_length=14)
    address = models.CharField(max_length=50)
    number = models.CharField(max_length=5)
    complement = models.CharField(max_length=30, blank=True)
    neighbourhood = models.CharField(max_length=30)
    cep = models.CharField(max_length=8)
    city = models.CharField(max_length=30)
    state = models.CharField(
        max_length=2,
        default='SP',
        choices=(
            ('AC', 'Acre'),
            ('AL', 'Alagoas'),
            ('AP', 'Amapá'),
            ('AM', 'Amazonas'),
            ('BA', 'Bahia'),
            ('CE', 'Ceará'),
            ('DF', 'Distrito Federal'),
            ('ES', 'Espírito Santo'),
            ('GO', 'Goiás'),
            ('MA', 'Maranhão'),
            ('MT', 'Mato Grosso'),
            ('MS', 'Mato Grosso do Sul'),
            ('MG', 'Minas Gerais'),
            ('PA', 'Pará'),
            ('PB', 'Paraíba'),
            ('PR', 'Paraná'),
            ('PE', 'Pernambuco'),
            ('PI', 'Piauí'),
            ('RJ', 'Rio de Janeiro'),
            ('RN', 'Rio Grande do Norte'),
            ('RS', 'Rio Grande do Sul'),
            ('RO', 'Rondônia'),
            ('RR', 'Roraima'),
            ('SC', 'Santa Catarina'),
            ('SP', 'São Paulo'),
            ('SE', 'Sergipe'),
            ('TO', 'Tocantins'),
        )
    )

    def __str__(self):
        return f'{self.user}'

    def clean(self):
        error_messages = {}

        cpf_sent = self.cpf or None
        cpf_saved = None
        profile = UserProfile.objects.filter(cpf=cpf_sent).first()

        if profile:
            cpf_saved = profile.cpf

            if cpf_saved is not None and self.pk != profile.pk:
                error_messages['cpf'] = 'CPF already taken.'


        if not validator.CPF_validate(self.cpf):
            error_messages['cpf'] = 'CPF invalid.'

        if re.search(r'[^0-9]', self.cep) or len(self.cep) != 8:
            error_messages['cep'] = 'Invalid CEP, insert just the 8 digits.'

        if error_messages:
            raise ValidationError(error_messages)

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

user/forms.py
from django.contrib.auth.models import User
from django import forms
from django.forms import fields
from . import models
import user

class ProfileForm(forms.ModelForm):
    class Meta:
        model = models.UserProfile
        fields = ('__all__')
        exclude = ('user', 'forget_password_token')

class UserForm(forms.ModelForm):
    password = forms.CharField(
        required=False,
        widget=forms.PasswordInput(),
        help_text=''
    )
    
    password_confirmation = forms.CharField(
        required=False,
        widget=forms.PasswordInput(),
        label='Confirm password'
    )

    def __init__(self, user=None, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.user = user
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password',
        'password_confirmation', 'email')
    
    def clean(self, *args, **kwargs):
        data = self.data
        cleaned = self.cleaned_data
        validation_error_msgs = {}

        user_data = cleaned.get('username')
        password_data = cleaned.get('password')
        password_confirmation_data = cleaned.get('password_confirmation')
        email_data = cleaned.get('email')


        user_db = User.objects.filter(username=user_data).first()
        email_db = User.objects.filter(email=email_data).first()

        error_msg_user_exists = 'Username already registered.'
        error_msg_email_exists = 'E-mail already registered.'
        error_msg_password_match = "Password and password confirmation doesn't match."
        error_msg_password_short = "Password too short, minimum of 6 characters."
        error_msg_required_field = "Field required."

        # Logged users: update
        if self.user:
            if user_db:
                if user_data != user_db.username:
                    new_user = User.objects.filter(username=user_data).first()

                    validation_error_msgs['username'] = error_msg_user_exists

            if email_db:
                if email_data != email_db.email:
                        validation_error_msgs['email'] = error_msg_email_exists

            if password_data:
                if password_data != password_confirmation_data:
                    validation_error_msgs['password'] = error_msg_password_match
                    validation_error_msgs['password_confirmation'] = error_msg_password_match

                if len(password_data) < 6:
                    validation_error_msgs['password'] = error_msg_password_short

        else:
            if user_db:
                validation_error_msgs['username'] = error_msg_user_exists

            if email_db:
                validation_error_msgs['email'] = error_msg_email_exists

            if not password_data:
                validation_error_msgs['password'] = error_msg_required_field

            if not password_confirmation_data:
                validation_error_msgs['password_confirmation'] = error_msg_required_field

            if password_data != password_confirmation_data:
                validation_error_msgs['password'] = error_msg_password_match
                validation_error_msgs['password_confirmation'] = error_msg_password_match

            if len(password_data) < 6:
                validation_error_msgs['password'] = error_msg_password_short

        if validation_error_msgs:
            raise(forms.ValidationError(validation_error_msgs))

user/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.views import View
from django.http import HttpResponse, request
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
import copy
import uuid
from utils.utils import reset_password

from . import models
from . import forms
import user

# Create your views here.

class ProfileBase(View):
    template_name = 'user/create.html'
    
    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)

        self.profile = 0
        self.cart = copy.deepcopy(self.request.session.get('cart', {}))

        if self.request.user.is_authenticated:
            self.profile = models.UserProfile.objects.filter(
                user=self.request.user
                ).first()

            self.context = {
                'userform': forms.UserForm(
                    data=self.request.POST or None,
                    user=self.request.user,
                    instance=self.request.user),
                'profileform': forms.ProfileForm(
                    data=self.request.POST or None,
                    instance=self.profile)
            }
        else:
            self.context = {
                'userform': forms.UserForm(
                    data=self.request.POST or None),
                'profileform': forms.ProfileForm(
                    data=self.request.POST or None)
            }

        self.userform = self.context['userform']
        self.profileform = self.context['profileform']

        if self.request.user.is_authenticated:
            self.template_name = 'user/update.html'

        self.render = render(self.request, self.template_name, self.context)

    def get(self, *args, **kwargs):
        return self.render


class Create(ProfileBase):
    def post(self, *args, **kwargs):
        if not self.userform.is_valid() or not self.profileform.is_valid():
            messages.error(
                self.request,
                'Invalid field(s).'
            )
            
            return self.render

        username = self.userform.cleaned_data.get('username')
        password = self.userform.cleaned_data.get('password')
        email = self.userform.cleaned_data.get('email')
        first_name = self.userform.cleaned_data.get('first_name')
        last_name = self.userform.cleaned_data.get('last_name')

        # User logged
        if self.request.user.is_authenticated:
            user = get_object_or_404(User, 
            username=self.request.user.username
            )
            
            user.username = username

            if password:
                user.set_password(password)

            user.email = email
            user.first_name = first_name
            user.last_name = last_name
            user.save()

            if not self.profile:
                self.profileform.cleaned_data['username'] = username
                profile = models.UserProfile(**self.profielform.cleaned_data)
                profile.save()
            else:
                profile = self.profileform.save(commit=False)
                profile.username = username
                profile.save()
            
            messages.success(
                self.request,
                "Update successful."
            )

        # New user
        else:
            user = self.userform.save(commit=False)
            user.set_password(password)
            user.save()

            profile = self.profileform.save(commit=False)
            profile.user = user
            profile.save()
            
            messages.success(
                self.request,
                "Registration successful."
            )

        if password:
            authenticate_user = authenticate(
                self.request,
                username=username,
                password=password
            )

            if authenticate_user:
                login(self.request, user=user)

        self.request.session['cart'] = self.cart
        self.request.session.save()


        return redirect('user:login')

class Login(View):
    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)
        self.template_name = 'user/login.html'
        self.render = render(self.request, self.template_name)

    def post(self, *args, **kwargs):
        username = self.request.POST.get('username')
        password = self.request.POST.get('password')

        if not username or not password:
            messages.error(
                self.request,
                'Username or password invalid.'
            )
            return redirect('user:create')

        user = authenticate(self.request,
        username=username, password=password)

        if not user:
            messages.error(
                self.request,
                'Username or password invalid.'
            )
            return redirect('user:create')

        login(self.request, user=user)

        messages.success(self.request, "Login successful.")

        if self.request.session.get('cart', {}):
            return redirect('product:shopresume')

        return redirect('product:list')

    def get(self, *args, **kwargs):
        return self.render

class Logout(View):
    def get(self, *args, **kwargs):

        if self.request.session.get('cart'):
            cart = copy.deepcopy(self.request.session.get('cart'))
        else:
            cart = False

        logout(self.request)

        if cart:
            self.request.session['cart'] = cart
            self.request.session.save()
        return redirect('product:list')
        
class ForgotPassword(View): 
    template_name='user/password_reset.html'

    def post(self, *args, **kwargs):
        email = self.request.POST.get('email')

        if not User.objects.filter(email=email).first():
            messages.success(
                self.request,
                'Email sent.'
            )
            return redirect('user:login')

        user = get_object_or_404(User, email=email)

        name = user.first_name
        user.set_password(reset_password(email, name, user))
        user.save()
        
        messages.success(
            self.request,
            'Email sent.'
        )

        return redirect('user:login')

    def get(self, *args, **kwargs):
        return render(self.request, self.template_name)

class ChangePassword(View):
    template_name = 'user/change_password.html'

    def post(self, *args, **kwargs):
        username = self.request.POST.get('username')
        temporary_password = self.request.POST.get('temporary_password')
        new_password = self.request.POST.get('new_password')
        new_password2 = self.request.POST.get('new_password2')

        if not username or not temporary_password or not new_password or not new_password2:
            messages.error(
                self.request,
                'Please fill all the fields bellow to proceed.'
            )
            return redirect('user:change_password')

        user_authentication = authenticate(
            self.request,
            username=username,
            password=temporary_password
        )

        user = get_object_or_404(User, username=username)

        if user_authentication is None:
            messages.error(
                self.request,
                'Username or temporary password invalid.'
            )
            return redirect('user:change_password')

        if new_password != new_password2:
            messages.error(
                self.request,
                'New password and password confirmation must be the same.'
            )
            return redirect('user:change_password')

        user.set_password(new_password)
        user.save()

        messages.success(
            self.request,
            'Password changed successfully.'
        )

        return redirect('user:login')

    def get(self, *args, **kwargs):
        return render(self.request, self.template_name)

user/templates/user/change_password.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Change Password | {% endblock title %}

{% block content %}

    <div class="row">

        <div class="col-lg mt-3">              
            <h4>Forgot my password</h4>
            <form class="mt-4" method="POST" action="{% url "user:change_password" %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="InputUsername">Username</label>
                    <input type="text" name="username"
                        class="form-control" id="InputUsername"
                        placeholder="Enter username">
                    <label class=" mt-3" for="InputPassword">Temporary password</label>
                    <input type="password" name="temporary_password"
                        class="form-control" id="InputPassword" placeholder="Enter temporary password">
                    <label class=" mt-3" for="InputPassword">New Password</label>
                    <input type="password" name="new_password"
                        class="form-control" id="InputPassword" placeholder="Enter new password">
                    <label class=" mt-3"  for="InputPassword">Confirm new password</label>
                    <input type="password" name="new_password2"
                        class="form-control" id="InputPassword" placeholder="Confirm new password">
                </div>
                <button type="submit" class="btn btn-primary btn-block btn-lg mt-5">Change password</button>
            </form>
        </div>

    </div>

{% endblock content %}

user/templates/user/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Create profile | {% endblock title %}

{% block content %}

    <div class="row">

        <div class="col-lg mt-3">

            {% block titleregister %}
                <h4>Register</h4>
            {% endblock titleregister %}

            <form method='POST' action="">
                {% csrf_token %}
                {{ userform|crispy }}
                {{ profileform|crispy }}

                <div class="row">
                    <div class="col">
                        <button type='submit' class='btn btn-primary btn-block btn-lg'>
                            Submit
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock content %}

user/templates/user/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Login | {% endblock title %}

{% block content %}

    <div class="row">

        <div class="col-lg mt-3">
            <h4>Login</h4>
            <form method="POST" action="{% url "user:login" %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="InputUsername">Username</label>
                    <input type="text" name="username"
                        class="form-control" id="InputUsername" aria-describedby="usernameHelp"
                        placeholder="Enter username">
                </div>
                <div class="form-group">
                    <label for="InputPassword">Password</label>
                    <input type="password" name="password"
                    class="form-control" id="InputPassword" placeholder="Enter password">
                </div>
                <p><a href="{% url 'user:password_reset' %}">Forgot my password</a></p>
                <button type="submit" class="btn btn-primary btn-block btn-lg">Login</button>
            </form>
            <p class='mt-3'>If you are not registered <a href="{% url 'user:create' %}">click here</a>.</p>
        </div>

    </div>

{% endblock content %}

user/templates/user/password_reset.html
{% extends 'base.html' %}

{% block title %}Forgot my password | {% endblock title %}

{% block content %}


    <div class="row">

        <div class="col-lg mt-3">
            <h4>Forgot my password</h4>
            <p class="mt-3">Enter your email bellow and we will send you an email with instructions to reset your password.</p>
            <form method="POST" action="{% url "user:password_reset" %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="InputEmail">Email</label>
                    <input type="text" name="email"
                        class="form-control" id="InputEmail" aria-describedby="EmailHelp"
                        placeholder="Enter email">
                </div>
                <button type="submit" class="btn btn-primary btn-block btn-lg mt-5">Send me instructions!</button>
            </form>
        </div>

    </div>

{% endblock content %}

user/templates/user/update.html
{% extends 'user/create.html' %}
{% load crispy_forms_tags %}

{% block title %}Update {{ user.first_name }}'s data | {% endblock title %}

{% block titleregister %}
    <h1>Update data</h1>
    <p>Use the following form to update your data.</p>
{% endblock titleregister %}