demand/urls.py
from django.urls import path
from . import views

app_name = 'demand'

urlpatterns = [
    path('pay/<int:pk>', views.Pay.as_view(), name='pay'),
    path('list/', views.List.as_view(), name='list'),
    path('savedemand/', views.SaveDemand.as_view(), name='savedemand'),
    path('detail/<int:pk>', views.Detail.as_view(), name='detail'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.ProductsList.as_view(), name='list'),
    path('<slug>', views.ProductDetails.as_view(), name='detail'),
    path('addtocart/', views.AddToCart.as_view(), name='addtocart'),
    path('removefromcart/', views.RemoveFromCart.as_view(), name='removefromcart'),
    path('cart/', views.Cart.as_view(), name='cart'),
    path('shopresume/', views.ShopResume.as_view(), name='shopresume'),
    path('search/', views.Search.as_view(), name='search'),
]

store/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('', include('product.urls')),
    path('user/', include('user.urls')),
    path('demand/', include('demand.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    path('', views.Create.as_view(), name='create'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('reset-password/', views.ForgotPassword.as_view(), name='password_reset'),
    path('change-password/', views.ChangePassword.as_view(), name='change_password'),
]

product/models.py
from django.db import models
from PIL import Image
import os
from django.conf import settings
from django.utils.text import slugify
from utils import utils

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=255)
    short_description = models.TextField(max_length=255)
    large_description = models.TextField()
    image = models.ImageField(
        upload_to='product_images/%Y/%m', blank=True, null=True
    )
    slug = models.SlugField(unique=True, blank=True, null=True)
    marketing_price = models.FloatField(verbose_name='Price')
    promotional_marketing_price = models.FloatField(default=0, verbose_name='Promotional Price')
    type = models.CharField(
        default='V',
        max_length=1,
        choices=(
            ('V', 'Variable'),
            ('S', 'Simple'),
        )
    )

    def get_formated_price(self):
        return utils.price_format(self.marketing_price)
    get_formated_price.short_description = 'Price'

    def get_formated_promotional_price(self):
        return utils.price_format(self.promotional_marketing_price)
    get_formated_promotional_price.short_description = 'Promotional Price'

    @staticmethod
    def resize_image(img, new_width=800):
        img_full_path = os.path.join(settings.MEDIA_ROOT, img.name)
        img_pil = Image.open(img_full_path)
        original_width, original_height = img_pil.size

        if original_width <= new_width:
            img_pil.close()
            return

        new_height = round((new_width * original_height) / original_width)

        new_img = img_pil.resize((new_width, new_height), Image.LANCZOS)
        new_img.save(
            img_full_path,
            optimize=True,
            quality=50
        )

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.name)}'
            self.slug = slug

        super().save(*args, **kwargs)

        max_image_size = 800

        if self.image:
            self.resize_image(self.image, max_image_size)

    def __str__(self):
        return self.name

class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, blank=True, null=True)
    price = models.FloatField()
    promotional_price = models.FloatField(default=0)
    inventory = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.name or self.product

    class Meta:
        verbose_name = 'Variation'
        verbose_name_plural = 'Variations'

product/views.py
from django import http
from django.contrib.auth.models import User
from django.contrib.messages.api import error
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from django.http import HttpResponse
from django.contrib import messages
from . import models
from user.models import UserProfile
import json
from django.core import serializers
from django.db.models import Q
# Create your views here.

class ProductsList(ListView):
    model = models.Product
    template_name = 'product/list.html'
    context_object_name = 'products'
    paginate_by = 10
    ordering = ['-id']

class Search(ProductsList):
    def get_queryset(self, *args, **kwargs):
        term = self.request.GET.get('term') or self.request.session['term']
        qs = super().get_queryset(*args, **kwargs)

        if not term:
            return qs

        self.request.session['term'] = term

        qs = qs.filter(
            Q(name__icontains=term) |
            Q(short_description__icontains=term) |
            Q(large_description__icontains=term)
        )

        self.request.session.save()

        return qs
class ProductDetails(DetailView):
    model = models.Product
    template_name = 'product/detail.html'
    context_object_name = 'product'
    slug_url_kwarg = 'slug'

class AddToCart(View):
    def get(self, *args, **kwargs):
        # if self.request.session.get('cart'):
        #     del self.request.session['cart']
        #     self.request.session.save()

        http_referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('product:list')
        )
        variation_id = self.request.GET.get('vid')

        if not variation_id:
            messages.error(
                self.request,
                'The product does not exist.'
            )

            return redirect(http_referer)

        variation = get_object_or_404(models.Variation, id=variation_id)
        variation_inventory = variation.inventory
        product = variation.product

        product_id = product.id
        product_name = product.name
        variation_name = variation.name or ''
        unit_price = variation.price
        unit_promotional_price = variation.promotional_price
        amount = 1
        slug = product.slug
        image = json.dumps(str(product.image))
        image_url = json.loads(image)

        if variation.inventory <1:
            messages.error(
                self.request,
                'Out of product.'
            )
            return redirect(http_referer)

        if not self.request.session.get('cart'):
            self.request.session['cart'] = {}
            self.request.session.save()

        cart = self.request.session['cart']

        if variation_id in cart:
            # TODO: variation exists in the cart
            cart_amount = cart[variation_id]['amount']
            cart_amount += 1

            if variation_inventory < cart_amount:
                messages.warning(
                    self.request,
                    f'Out of inventory for {cart_amount}x in product "{product_name}". '
                    f'We added {variation_inventory}x the product in your cart.'
                )
                cart_amount = variation_inventory
            
            cart[variation_id]['amount'] = cart_amount
            cart[variation_id]['quantitative_price'] = unit_price * cart_amount
            cart[variation_id]['quantitative_promotional_price'] = unit_promotional_price * cart_amount

        else:
            cart[variation_id] = {
                'product_id' : product_id,
                'product_name' : product_name,
                'variation_name' : variation_name,
                'variation_id' : variation_id,
                'unit_price' : unit_price,
                'unit_promotional_price' : unit_promotional_price,
                'quantitative_price' : unit_price,
                'quantitative_promotional_price' : unit_promotional_price,
                'amount' : amount,
                'slug' : slug,
                'image' : image,
                'image_url' : image_url
            }

        self.request.session.save()
        messages.success(
            self.request,
            f'Product {product_name} {variation_name} added to the cart '
            f'{cart[variation_id]["amount"]}x.'
        )

        return redirect(http_referer)

class RemoveFromCart(View):
    def get(self, *args, **kwargs):
        http_referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('product:list')
        )
        variation_id = self.request.GET.get('vid')

        if not variation_id:
            return redirect(http_referer)

        if not self.request.session.get('cart'):
            return redirect(http_referer)

        if variation_id not in self.request.session['cart']:
            return redirect(http_referer)

        cart = self.request.session['cart'][variation_id]

        messages.success(
            self.request,
            f'Product "{cart["product_name"]} {cart["variation_name"]} removed from cart."'
        )

        del self.request.session['cart'][variation_id]
        self.request.session.save()
        return redirect(http_referer)

class Cart(View):
    def get(self, *args, **kwargs):
        context = {
            'cart' : self.request.session.get('cart', {})
        }
        return render(self.request, 'product/cart.html', context)

class ShopResume(View):
    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('profile:login')

        profile = UserProfile.objects.filter(user=self.request.user).exists()

        if not profile:
            messages.error(
                self.request,
                'User without profile.'
            )
            return redirect('user:create')

        if not self.request.session.get('cart'):
            messages.error(
                self.request,
                'Empty cart.'
            )
            return redirect('product:list')

        context = {
            'user': self.request.user,
            'cart': self.request.session['cart'],
        }
        return render(self.request, 'product/shopresume.html', context)

# class CreateCheckoutSessionView(View):
#     def

product/templates/product/cart.html
{% extends 'base.html' %}
{% load static %}
{% load omfilters %}

{% block title %}Cart | {% endblock %}

{% block content %}

    {% if cart %}

        <div class="row mt-3">
            <div class="col">
                <h3>Shopping Cart</h3>
                <p class="lead">The products, amounts and prices you chose.</p>

            {% include 'partial/_cart.html' %}

            </div>
        </div>



        <div class="row mt-3">
            <div class="col-lg">
                <p class='lead'>Total in cart</p>

                <div class='table-responsive'>
                    <table class="table">
                        <tr>
                            <td class="font-weight-bold">Total</td>
                            <td>{{ cart|cart_totals|price_format }}</td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="col-lg mt-auto">

                {% if request.user.is_authenticated %}
                    <a class="btn btn-lg btn-block btn-primary" href="{% url 'product:shopresume' %}">
                        Buy
                    </a>
                {% else %}
                    <a class="btn btn-lg btn-block btn-primary" href="{% url 'user:login' %}">
                        Login
                    </a>
                {% endif %}
            </div>
        </div>

    {% else %}

        <div class="row mt-3">
            <div class="col">
                <h3>Empty Cart</h3>
                <p class="lead">No products in cart.</p>
            </div>
        </div>

    {% endif %}

{% endblock %}

product/templates/product/detail.html
{% extends 'base.html' %}
{% load omfilters %}

{% block title %}{{ product.name }} | {% endblock title %}

{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                <div class="col-lg">
                    <div class="row no-gutters">
                        <div class="col-lg-12">
                            {% if product.image %}
                                <img class="img-fluid" src="{{ product.image.url }}">
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-lg">
                    <div class="mt-4 mt-lg-0">
                        <h1 class="h2">{{ product.name }}</h1>
                        <p class="lead">{{ product.short_description }}</p>
                        <p class="lead">
                        {% if product.promotional_marketing_price %}
                            <span id="variation-preco-promocional" class="lead product-price">
                                {{ product.promotional_marketing_price|price_format }}
                            </span>
                            <span id="variation-preco"
                                class="lead product-old-price text-muted">
                                {{ product.marketing_price|price_format }}
                            </span>
                        {% else %}
                            <span id="variation-preco" class="lead product-price">
                                {{ product.marketing_price|price_format }}
                            </span
                        {% endif %}
                        </p>

                        <form action="{% url 'product:addtocart' %}" id="form-add-to-cart">
                            <div class="form-group">
                                <select id="select-variacoes" name="vid" class="form-control form-control-lg">
                                    {% for variation in product.variation_set.all %}

                                        {% if variation.promotional_price %}
                                            <option data-preco="{{ variation.price|price_format }}" 
                                            data-preco-promocional="{{ variation.promotional_price|price_format }}" value="{{ variation.id }}">
                                                {% if variation.name %}
                                                    {{ variation.name }}
                                                {% else %}
                                                    {{ variation }}
                                                {% endif %}
                                            </option>
                                        {% else %}
                                            <option data-preco-promocional="{{ variation.price|price_format }}" 
                                            value="{{ variation.id }}">
                                                {% if variation.name %}
                                                    {{ variation.name }}
                                                {% else %}
                                                    {{ variation }}
                                                {% endif %}
                                            </option>
                                        {% endif %}

                                    {% endfor %}
                                </select>
                            </div>

                            <div class="text-left">
                                <button type="submit" class="btn btn-primary btn-lg btn-block">
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                    Add to cart
                                </button>
                            </div>

                        </form>


                    </div>
                </div>
            </div>  
        </div>  


    <div class="row">
        <div class="col-lg-12">
            <div class="mt-5 mb-5">
                <h2 class="text-center">{{ product.name }}</h2>
                {{ product.large_description|linebreaks }}
            </div>
        </div>
    </div>

{% endblock %}

product/templates/product/list.html
{% extends 'base.html' %}
{% load omfilters %}

{% block title %}Home | {% endblock title %}

{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <div class="card-columns">

                {% for product in products %}

                    <div class="card">

                        {% if product.image %}
                            <a href="{% url 'product:detail' product.slug %}">
                                <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.name }}">
                            </a>
                        {% endif %}

                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <p class="card-text">{{ product.short_description }}</p>
                            <div class="container product-price-block text-center">

                                {% if product.promotional_marketing_price %}
                                    <span class="product-price">
                                        {{ product.promotional_marketing_price|price_format }}
                                    </span>
                                    <span class="product-old-price text-muted">
                                        {{ product.marketing_price|price_format }}
                                    </span>
                                {% else %}
                                    <span class="productprice">
                                        {{ product.marketing_price|price_format }}
                                    </span>
                                {% endif %}

                            </div>
                        </div>
                        <div class="card-footer bg-transparent border-top-light-custom text-center">
                            <a href="{% url 'product:detail' product.slug %}" class="btn btn-primary btn-sm m-1 btn-block">
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                Comprar
                            </a>
                        </div>
                    </div>

                {% endfor %}
            </div>

        </div>
    </div>

<div class="row mt-3">
    <div class="col">
        {% include 'partial/_pagination.html' %}
    </div>
</div>

{% endblock %}

product/templates/product/shopresume.html
{% extends 'base.html' %}
{% load omfilters %}

{% block title %}Shop resume | {% endblock title %}

{% block content %}

    <div class="row mb-5">
        <div class="col-lg">
            <h2>Shop resume</h2>

            <p class="lead">User data</p>
            <p>In case you need to edit it, <a href="{% url 'user:create' %}">clck here</a>.</p>
            <dl class="row">
                <dt class="col-lg-2">Name:</dt>
                <dd class="col-lg-4">{{ user.first_name }}</dd>
                <dt class="col-lg-2">Surname:</dt>
                <dd class="col-lg-4">{{ user.last_name }}</dd>

                <dt class="col-lg-2">CPF:</dt>
                <dd class="col-lg-4">{{ user.userprofile.cpf }}</dd>
                <dt class="col-lg-2">E-mail:</dt>
                <dd class="col-lg-4">{{ user.email }}</dd>
            </dl>

            <p class="lead">Address data</p>
            <p>In case you want to edit it, <a href="{% url 'user:create' %}">clck here</a>.</p>
            <dl class="row">
                <dt class="col-lg-2">Address:</dt>
                <dd class="col-lg-4">{{ user.userprofile.address }}</dd>
                <dt class="col-lg-2">Number:</dt>
                <dd class="col-lg-4">{{ user.userprofile.number }}</dd>

                {% if user.userprofile.complement %}
                    <dt class="col-lg-2">Complement:</dt>
                    <dd class="col-lg-4">{{ user.userprofile.complement }}</dd>
                {% endif %}

                <dt class="col-lg-2">Neighbourhood:</dt>
                <dd class="col-lg-4">{{ user.userprofile.neighbourhood }}</dd>

                <dt class="col-lg-2">City:</dt>
                <dd class="col-lg-4">{{ user.userprofile.city }}</dd>
                <dt class="col-lg-2">State:</dt>
                <dd class="col-lg-4">{{ user.userprofile.state }}</dd>

                <dt class="col-lg-2">Postal code:</dt>
                <dd class="col-lg-4">{{ user.userprofile.cep }}</dd>
            </dl>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col">
            <h3>Cart resume</h3>
            <p class="lead">The products, amounts and prices you chose.</p>

        {% include 'partial/_cart.html' %}

        </div>
    </div>
    <div class="row mt-3">
        <div class="col">
            <p class="lead text-center"><span class="font-weight-bold"> Total:</span> {{ cart|cart_totals|price_format }}</p>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <a class="btn btn-block btn-primary btn-lg" href="{% url 'demand:savedemand' %}">
                Choose payment method
            </a>
        </div>
    </div>

{% endblock content %}