demand/urls.py
from django.urls import path
from . import views

app_name = 'demand'

urlpatterns = [
    path('pay/<int:pk>', views.Pay.as_view(), name='pay'),
    path('list/', views.List.as_view(), name='list'),
    path('savedemand/', views.SaveDemand.as_view(), name='savedemand'),
    path('detail/<int:pk>', views.Detail.as_view(), name='detail'),
]

store/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('', include('product.urls')),
    path('user/', include('user.urls')),
    path('demand/', include('demand.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    path('', views.Create.as_view(), name='create'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('reset-password/', views.ForgotPassword.as_view(), name='password_reset'),
    path('change-password/', views.ChangePassword.as_view(), name='change_password'),
]

demand/models.py
from product.models import Product
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Demand(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.FloatField()
    total_amount = models.PositiveIntegerField()
    status = models.CharField(
        default="C",
        max_length=1,
        choices=(
            ('A', 'Approved'),
            ('R', 'Rejected'),
            ('C', 'Created'),
            ('P', 'Pending'),
            ('S', 'Sent'),
            ('F', 'Finished'),
        )
    )

    def __str__(self):
        return f'Request N. {self.pk}'

class DemandItem(models.Model):
    demand = models.ForeignKey(Demand, on_delete=models.CASCADE)
    product = models.CharField(max_length=255)
    product_id = models.PositiveIntegerField()
    variation = models.CharField(max_length=255)
    variation_id = models.PositiveIntegerField()
    price = models.FloatField()
    promotional_price = models.FloatField(default=0)
    amount = models.PositiveIntegerField()
    image = models.CharField(max_length=2000)

    def __str__(self):
        return f"{self.demand}'s item"

    class Meta:
        verbose_name = 'Request item'
        verbose_name_plural = 'Request items'

demand/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import ListView, DetailView
from django.views import View
from django.http import HttpResponse
from django.contrib import messages
from product.models import Variation
from utils import utils
from .models import Demand, DemandItem
import json
# Create your views here.

class DispatchLoginRequiredMixin(View):
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('user:login')

        return super().dispatch(*args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(user=self.request.user)
        
        return qs

class Pay(DispatchLoginRequiredMixin, DetailView):
    #TODO: Add payment method (Use stripe)
    # tutorial:  https://www.youtube.com/watch?v=oZwyA9lUwRk&ab_channel=DennisIvy
    template_name = 'demand/pay.html'
    model = Demand
    pk_url_kwarg = 'pk'
    context_object_name = 'demand'


class SaveDemand(View):

    template_name = 'demand/pay.html'

    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.error(
                self.request,
                'You have to be login to finish your purchase.'
            )
            return redirect('user:login')

        if not self.request.session.get('cart'):
            messages.error(
                self.request,
                'Empty cart.'
            )
            return redirect('product:list')


        cart = self.request.session.get('cart')
        cart_variation_ids = [v for v in cart]
        bd_variations = list(
            Variation.objects.select_related('product')
            .filter(id__in=cart_variation_ids)
        )

        for variation in bd_variations:
            vid = str(variation.id)

            inventory = variation.inventory
            cart_amount = cart[vid]['amount']
            unit_price = cart[vid]['unit_price']
            unit_promotional_price = cart[vid]['unit_promotional_price']

            error_msg_inventory = ''
            
            if inventory < cart_amount:
                cart[vid]['amount'] = inventory
                cart[vid]['quantitative_price'] = inventory*unit_price
                cart[vid]['quantitative_promotional_price'] = inventory*unit_promotional_price

                error_msg_inventory = 'Some products you chose might not have the amount you wish in inventory. '\
                    'Amounts updated according to the inventory, please verify your new amounts.'

            if error_msg_inventory:
                messages.error(
                    self.request,
                    error_msg_inventory
                )
                
                self.request.session.save()
                return redirect('product:cart')

        cart_total_amount = utils.cart_total_amount(cart)
        cart_total_value = utils.cart_totals(cart)

        demand = Demand(
            user=self.request.user,
            total=cart_total_value,
            total_amount=cart_total_amount,
            status='C',
        )

        demand.save()

        DemandItem.objects.bulk_create(
            [
                DemandItem(
                    demand=demand,
                    product=v['product_name'],
                    product_id=v['product_id'],
                    variation=v['variation_name'],
                    variation_id=v['variation_id'],
                    price=v['quantitative_price'],
                    promotional_price=v['quantitative_promotional_price'],
                    amount=v['amount'],
                    image=json.loads(v['image']),
                ) for v in cart.values()
            ]
        )

        del self.request.session['cart']

        return redirect(
            reverse(
                'demand:pay',
                kwargs={
                    'pk': demand.pk
                }
            )
        )


class Detail(DispatchLoginRequiredMixin, DetailView):
    model = Demand
    context_object_name = 'demand'
    template_name = 'demand/detail.html'
    pk_url_kwarg = 'pk'

class List(DispatchLoginRequiredMixin, ListView):
    model = Demand
    context_object_name = 'demands'
    template_name = 'demand/list.html'
    paginate_by = 10
    ordering = ['-id']

demand/templates/demand/detail.html
{% extends 'base.html' %}
{% load omfilters %}
{% load static %}

{% block title %}{{ demand }} | {% endblock title %}

{% block content %}

    {% include 'partial/_demand.html' %}

{% endblock content %}

demand/templates/demand/list.html
{% extends 'base.html' %}
{% load omfilters %}

{% block title %}{{ user.first_name }}'s demands | {% endblock title %}

{% block content %}

    <div class="row">
        <div class="col">
            <h3 class="mb-4">{{ user }}'s demand</h3>
            <p>You will find all the products you selected bellow.</p>

            <div class="table-responsive">
                <table class="table table-striped">

                    <tr>
                        <th scope="col">Pedido</th>
                        <th scope="col">Total</th>
                        <th scope="col">Qtd. Itens</th>
                        <th scope="col">Status</th>
                        <th scope="col">Mais detalhes</th>
                    </tr>

                    {% for demand in demands %}
                        <tr>
                            <th scope="row">{{ demand }}</td>
                            <td>{{ demand.total|price_format }}</td>
                            <td>{{ demand.total_amount }}</td>
                            <td>{{ demand.get_status_display }}</td>
                            <td>
                                <a href="{% url 'demand:detail' demand.id %}">
                                    See details <i class="fas fa-search-plus ml-2"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}

                </table>
            </div>
        </div>
    </div>

{% include 'partial/_pagination.html' %}

{% endblock content %}

demand/templates/demand/pay.html
{% extends 'base.html' %}
{% load omfilters %}
{% load static %}

{% block title %}Payment | {% endblock title %}

{% block content %}

    <div class="row">
        <div class="col">
            <h3>Choose the payment method</h3>
        </div>
    </div>

    {% include 'partial/_demand.html' %}
    
    <div class="row mt-4">
        <div class="col">
            <a href="#" class="btn btn-primary btn-block btn-lg">Pay</a>
        </div>
    </div>

{% endblock content %}