demand/urls.py
from django.urls import path
from . import views

app_name = 'demand'

urlpatterns = [
    path('pay/<int:pk>', views.Pay.as_view(), name='pay'),
    path('list/', views.List.as_view(), name='list'),
    path('savedemand/', views.SaveDemand.as_view(), name='savedemand'),
    path('detail/<int:pk>', views.Detail.as_view(), name='detail'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.ProductsList.as_view(), name='list'),
    path('<slug>', views.ProductDetails.as_view(), name='detail'),
    path('addtocart/', views.AddToCart.as_view(), name='addtocart'),
    path('removefromcart/', views.RemoveFromCart.as_view(), name='removefromcart'),
    path('cart/', views.Cart.as_view(), name='cart'),
    path('shopresume/', views.ShopResume.as_view(), name='shopresume'),
    path('search/', views.Search.as_view(), name='search'),
]

store/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('', include('product.urls')),
    path('user/', include('user.urls')),
    path('demand/', include('demand.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    path('', views.Create.as_view(), name='create'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('reset-password/', views.ForgotPassword.as_view(), name='password_reset'),
    path('change-password/', views.ChangePassword.as_view(), name='change_password'),
]

demand/models.py
from product.models import Product
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Demand(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.FloatField()
    total_amount = models.PositiveIntegerField()
    status = models.CharField(
        default="C",
        max_length=1,
        choices=(
            ('A', 'Approved'),
            ('R', 'Rejected'),
            ('C', 'Created'),
            ('P', 'Pending'),
            ('S', 'Sent'),
            ('F', 'Finished'),
        )
    )

    def __str__(self):
        return f'Request N. {self.pk}'

class DemandItem(models.Model):
    demand = models.ForeignKey(Demand, on_delete=models.CASCADE)
    product = models.CharField(max_length=255)
    product_id = models.PositiveIntegerField()
    variation = models.CharField(max_length=255)
    variation_id = models.PositiveIntegerField()
    price = models.FloatField()
    promotional_price = models.FloatField(default=0)
    amount = models.PositiveIntegerField()
    image = models.CharField(max_length=2000)

    def __str__(self):
        return f"{self.demand}'s item"

    class Meta:
        verbose_name = 'Request item'
        verbose_name_plural = 'Request items'

demand/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import ListView, DetailView
from django.views import View
from django.http import HttpResponse
from django.contrib import messages
from product.models import Variation
from utils import utils
from .models import Demand, DemandItem
import json
# Create your views here.

class DispatchLoginRequiredMixin(View):
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('user:login')

        return super().dispatch(*args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(user=self.request.user)
        
        return qs

class Pay(DispatchLoginRequiredMixin, DetailView):
    #TODO: Add payment method (Use stripe)
    # tutorial:  https://www.youtube.com/watch?v=oZwyA9lUwRk&ab_channel=DennisIvy
    template_name = 'demand/pay.html'
    model = Demand
    pk_url_kwarg = 'pk'
    context_object_name = 'demand'


class SaveDemand(View):

    template_name = 'demand/pay.html'

    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.error(
                self.request,
                'You have to be login to finish your purchase.'
            )
            return redirect('user:login')

        if not self.request.session.get('cart'):
            messages.error(
                self.request,
                'Empty cart.'
            )
            return redirect('product:list')


        cart = self.request.session.get('cart')
        cart_variation_ids = [v for v in cart]
        bd_variations = list(
            Variation.objects.select_related('product')
            .filter(id__in=cart_variation_ids)
        )

        for variation in bd_variations:
            vid = str(variation.id)

            inventory = variation.inventory
            cart_amount = cart[vid]['amount']
            unit_price = cart[vid]['unit_price']
            unit_promotional_price = cart[vid]['unit_promotional_price']

            error_msg_inventory = ''
            
            if inventory < cart_amount:
                cart[vid]['amount'] = inventory
                cart[vid]['quantitative_price'] = inventory*unit_price
                cart[vid]['quantitative_promotional_price'] = inventory*unit_promotional_price

                error_msg_inventory = 'Some products you chose might not have the amount you wish in inventory. '\
                    'Amounts updated according to the inventory, please verify your new amounts.'

            if error_msg_inventory:
                messages.error(
                    self.request,
                    error_msg_inventory
                )
                
                self.request.session.save()
                return redirect('product:cart')

        cart_total_amount = utils.cart_total_amount(cart)
        cart_total_value = utils.cart_totals(cart)

        demand = Demand(
            user=self.request.user,
            total=cart_total_value,
            total_amount=cart_total_amount,
            status='C',
        )

        demand.save()

        DemandItem.objects.bulk_create(
            [
                DemandItem(
                    demand=demand,
                    product=v['product_name'],
                    product_id=v['product_id'],
                    variation=v['variation_name'],
                    variation_id=v['variation_id'],
                    price=v['quantitative_price'],
                    promotional_price=v['quantitative_promotional_price'],
                    amount=v['amount'],
                    image=json.loads(v['image']),
                ) for v in cart.values()
            ]
        )

        del self.request.session['cart']

        return redirect(
            reverse(
                'demand:pay',
                kwargs={
                    'pk': demand.pk
                }
            )
        )


class Detail(DispatchLoginRequiredMixin, DetailView):
    model = Demand
    context_object_name = 'demand'
    template_name = 'demand/detail.html'
    pk_url_kwarg = 'pk'

class List(DispatchLoginRequiredMixin, ListView):
    model = Demand
    context_object_name = 'demands'
    template_name = 'demand/list.html'
    paginate_by = 10
    ordering = ['-id']

templates/partial/_cart.html
{% load static %}
{% load omfilters %}

<div class="table-responsive">
    <table class="table">
        <tr>
            <th class="d-none d-lg-block">Image</th>
            <th>Product</th>
            <th>Value</th>
            <th>Amount</th>
            <th>Total</th>
        </tr>

        {% for item in cart.values %}

            <tr>
                <td class="d-none d-lg-block">
                    <a href="{% url 'product:detail' item.slug %}">
                        <img class="cart-img" src="{% get_media_prefix %}{{ item.image_url }}">
                    </a>
                </td>
                <td>
                    <a href="{% url 'product:detail' item.slug %}">
                        {{ item.product_name }}
                    </a>
                    <a class="ml-3" href="{% url 'product:removefromcart' %}?vid={{ item.variation_id }}">
                        <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
                    </a>
                </td>
                <td>{{ item.variation_name }}</td>
                <td>
                    {{ item.amount }} x 
                    {% if item.unit_promotional_price %}

                        {{ item.unit_promotional_price|price_format }}

                    {% else %}

                        {{ item.unit_price|price_format }}
                    
                    {% endif %}
                </td>

                {% if item.quantitative_promotional_price %}
                
                    <td>{{ item.quantitative_promotional_price|price_format }}</td>

                {% else %}
                
                    <td>{{ item.quantitative_price|price_format }}</td>
                
                {% endif %}

            </tr>
        {% endfor %}

    </table>
</div>

templates/partial/_demand.html
{% load static %}
{% load omfilters %}

<div class="row">
    <div class="col">
        <h3>{{ demand }}</h3>

        <div class="row mt-4">
            <div class="col-lg-2 font-weight-bold">Request number:</div>
            <div class="col-lg-4">{{ demand.id }}</div>
            <div class="col-lg-2 font-weight-bold">Total:</div>
            <div class="col-lg-4">{{ demand.total|price_format }}</div>

            <div class="col-lg-2 font-weight-bold">Itens' amount:</div>
            <div class="col-lg-4">{{ demand.total_amount }}</div>
            <div class="col-lg-2 font-weight-bold">Status:</div>
            <div class="col-lg-4">{{ demand.get_status_display }}</div>
        </div>

        <div class="row mt-4">
            <div class="col">
                <h3>Products</h3>
            </div>
        </div>

        <div class="table-responsive mt-3">
            <table class="table">
                <tr>
                    <th class="d-none d-lg-block">Image</th>
                    <th>Product</th>
                    <th>Variation</th>
                    <th>Amount</th>
                    <th>Total</th>
                </tr>

                {% for line in demand.demanditem_set.all %}
                    <tr>
                        <td class="d-none d-lg-block">
                            <img class="cart-img" src="{% get_media_prefix %}{{ line.image }}">
                        </td>
                        <td>{{ line.product }}</td>
                        <td>{{ line.variation }}</td>
                        <td>{{ line.amount }}</td>
                        <td>
                            {% if line.promotional_price %}
                                {{ line.promotional_price|price_format }}
                            {% else %}
                                {{ line.price|price_format }}
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>

    </div>
</div>

templates/partial/_footer.html
{% load static %}

<footer class="container-fluid bg-primary">
    <div class="container text-light">
        <div class="row">
            <div class="col">
                <div class="p-1">
                    <span class="align-middle p-1">Made with Django</span>
                </div>
            </div>
            <div class="col">
                <div class="p-1 text-right">
                    <span class="align-middle p-1">By Gabriel Rosin</span>
                </div>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'assets/bootstrap/js/jquery-3.2.1.slim.min.js'%}"></script>
<script src="{% static 'assets/bootstrap/js/popper.min.js'%}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js'%}"></script>
<script defer src="{% static 'assets/font-awesome/js/all.js'%}"></script>
<script src="{% static 'assets/custom/js/scripts.js'%}"></script>

templates/partial/_head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.css'%}">
<link rel="stylesheet" href="{% static 'assets/custom/css/style.css'%}">

templates/partial/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/partial/_nav.html
{% load static %}
{% load omfilters %}

<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
    <a class="navbar-brand" href="{% url 'product:list' %}">MyItems</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">

            {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Account
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'demand:list' %}">My demands</a>
                        <a class="dropdown-item" href="{% url 'user:create' %}">Update my data</a>
                        <a class="dropdown-item" href="{% url 'user:logout' %}">Logout</a>
                    </div>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:login' %}">Login</a>
                </li>
            {% endif %}

            {% if request.session.cart %}

                <li class="nav-item">
                    <a class="nav-link nav-cart-link active" href="{% url 'product:cart' %}">
                        <span class="nav-cart-count mr-1">
                            <strong>{{ request.session.cart|cart_total_amount }}x</strong>
                        </span>
                        <span class="nav-cart-icon mr-2">
                            <i class="fas fa-shopping-cart"></i>
                        </span>
                    </a>
                </li>

            {% endif %}

        </ul>
        <form class="form-inline my-2 my-lg-0" method ="GET" action="{% url 'product:search' %}">
            <input name='term' value="{{ request.GET.term }}" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

templates/partial/_pagination.html
{% if is_paginated %}

<div class="col mt-3 mb-3">
    <div class="row">
        <div class="pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">&laquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
                </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}

                {% if page_obj.number == num %}
                <li class="page-item active">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% endif %}

                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

{% endif %}